### ISSUE TITLE
Integrate changes from other forks?

### ISSUE THREAD

**Issue by norrisjeremy** [patrodyne/hisrc-higherjaxb#1]
Will you be looking at integrating changes from other forks, such as https://github.com/evolvedbinary/jvnet-jaxb-maven-plugin?

**Comment by patrodyne** [comment]
Jeremy, I have updated the README with my next [goals](https://github.com/patrodyne/hisrc-higherjaxb#goals) for this repository. My plan is to work slowly, with incremental commits and occasional releases, until all dependencies are updated to current versions. My overall goal, for the near term, is to include the new *jakarta* namespace. After that, I'll consider new features.

**Comment by vetrivendhan** [comment]
Hi @patrodyne When will it be released in the Maven central?

**Comment by patrodyne** [comment]
Hi @vetrivendhan, all the libraries (hisrc-xxx.jar) have been released to the Maven Central Repository. See the [README.md](https://github.com/patrodyne/hisrc-higherjaxb#maven-central-repository) for the Maven Search and Index links.

**Comment by vetrivendhan** [comment]
Thanks, @patrodyne for the response. But the version which is in Maven (0.6.3) doesn't seem to support the Jakarta JAXB libraries. Can you please let me know if this support is to be added in near future?

**Comment by patrodyne** [comment]
I do not have dates for the next release. I will keep the [README.md](https://github.com/patrodyne/hisrc-higherjaxb#readme) updated with my current goals and status. Currently, I am working on new sample projects to explore features and further verify the current build. After that, I plan to slowly update dependencies to new versions but short of the Jakarta namespace conversation. When I am confident of the pre-Jakarta build(s) then I'll look at conversion to the Jakarta build which will be several releases away.

**Comment by vetrivendhan** [comment]
Thanks for the prompt update @patrodyne . Appreciate your kind response!!
