### ISSUE TITLE
Error with GitLab Gemnasium dependency scanning

### ISSUE THREAD

**Issue by dorkest-dork** [patrodyne/hisrc-higherjaxb#3]
Hi!

We'are using hisrc-higherjaxb30-maven-plugin in our project and using Gemnasium dependency scanning in GitLab CICD pipeline.
When we took your plugin into use, Gemnasium job fails with error "**The plugin org.patrodyne.jvnet:hisrc-higherjaxb30-maven-plugin:2.1.1 requires Maven version 3.8.4**".
Our CICD configuration uses https://gitlab.com/gitlab-org/gitlab-foss/blob/master/lib/gitlab/ci/templates/Jobs/Dependency-Scanning.gitlab-ci.yml and the image (according to logs) seems to be registry.gitlab.com/security-products/gemnasium-maven:4.
So, is your plugin bound to Maven 3.8.4 or is this GitLab's problem?

BR,
Dork

**Comment by dorkest-dork** [comment]
It seems that this is GitLab's issue ATM https://gitlab.com/gitlab-org/gitlab/-/issues/414022

**Comment by patrodyne** [comment]
Reported as a GitLab issue.
