### ISSUE TITLE
Missing DependencyFilterUtils on Maven < 3.9.0

### ISSUE THREAD

**Issue by runeflobakk** [patrodyne/hisrc-higherjaxb#7]
Hello, thank you for the 2.2.0 release!
Just wanted to give a heads-up that using the 2.2.0 plugin on GitHub actions will fail with the default Maven setup offered currently by the latest setup-java@v4, as the Maven version is 3.8.8, and the plugin really requires [Maven 3.9.0](https://github.com/patrodyne/hisrc-higherjaxb/commit/0f15436562719d8e597b20321eac8ae0b2302b44).

Running the plugin in this environment will give the following error:

```
Error: Failed to execute goal org.patrodyne.jvnet:hisrc-higherjaxb-maven-plugin:2.2.0:generate (default)
on project myproject: Execution default of goal org.patrodyne.jvnet:hisrc-higherjaxb-maven-plugin:2.2.0:generate
failed: A required class was missing while executing org.patrodyne.jvnet:hisrc-higherjaxb-maven-plugin:2.2.0:generate:
org/eclipse/aether/util/filter/DependencyFilterUtils
```

The `DependencyFilterUtils` class can be found in maven-resolver-util, and adding it as a declared dependency to the plugin will enable the execution to complete successfully:

```xml
<plugin>
    <groupId>org.patrodyne.jvnet</groupId>
    <artifactId>hisrc-higherjaxb-maven-plugin</artifactId>
    <version>2.2.0</version>
    <dependencies>
        <dependency>
            <groupId>org.apache.maven.resolver</groupId>
            <artifactId>maven-resolver-util</artifactId>
            <version>1.9.18</version>
        </dependency>
    </dependencies>
</plugin>
```

Earlier versions will also work. I tested with 1.6.2.

They seem unwilling to upgrade and/or add any configuration support to set Maven version in the official setup-java action: https://github.com/actions/setup-java/issues/457 and instead refer to community actions for providing specific Maven versions on GitHub Actions.

**Comment by patrodyne** [comment]
Thank you for the report. I have updated the `maven-min.version` / `requireMavenVersion` in the `maven-enforcer-plugin` to `3.9.0` for the next release.

**Comment by runeflobakk** [comment]
Just curious, but are you using any Maven Plugin API version 3.9.0-specific features, or would it be possible to downgrade to v3.8.8 to make the plugin work out-of-the-box on GitHub actions?

**Comment by patrodyne** [comment]
Yes, since v2.2.0, the _HiSrc HigherJAXB Maven Plugins_ have been refactored to eliminate the deprecated [`maven-compat`][11] dependency in favor of the Maven Resolver/Aether dependencies, Issue patrodyne/hisrc-basicjaxb#17 and Issue #2.

[11]: https://cwiki.apache.org/confluence/display/MAVEN/Plugin+migration+to+Maven3+dependencies
